"""PhysCF - Physics-Informed Counterfactual Explanations for Groundwater Forecasting.

Integrated into time-serie-explo for use with Darts models (TFT, GRU, etc.).
"""

from .perturbation import PerturbationLayer
from .darts_adapter import DartsModelAdapter
from .physcf_optim import generate_counterfactual
from .optuna_optim import generate_counterfactual_optuna
from .comet_hydro import generate_counterfactual_comet
from .types import CounterfactualResult
from .ips import (
    IPS_CLASSES,
    IPS_ORDER,
    IPS_WINDOWS,
    BRGM_MIN_YEARS,
    AQUIFER_IPS_WINDOW,
    AQUIFER_CATEGORY,
    compute_ips_reference,
    compute_ips_reference_n,
    compute_all_ips_references,
    compute_ips_series,
    compute_ips_series_n,
    compute_rolling_monthly_mean,
    validate_ips_data,
    get_aquifer_ips_info,
    daily_to_monthly_mean,
    gwl_to_ips_class,
    gwl_to_ips_zscore,
    ips_class_to_gwl_bounds,
    extract_scaler_params,
    ref_stats_to_json,
    ref_stats_from_json,
    compute_monthly_ips_bounds,
    classify_prediction_monthly,
)
from .pastas_validation import (
    PASTAS_AVAILABLE,
    PastasWrapper,
    compute_rmse,
    validate_with_pastas,
    fit_pastas_for_station,
    build_pastas_series_from_data,
    cf_stresses_to_pastas_series,
    run_dual_validation_for_results,
)
from .metrics import (
    validity_ratio,
    stepwise_validity,
    seasonal_validity,
    proximity_theta,
    proximity_l1,
    proximity_l2,
    mean_absolute_change,
    max_absolute_change,
    relative_change_pct,
    temporal_sparsity,
    channel_sparsity,
    total_variation,
    cc_compliance,
    cc_compliance_from_theta,
    cc_compliance_from_stresses,
    pastas_agreement,
    param_count,
    convergence_iter,
    wall_clock_seconds,
    build_paper_metrics,
)

__all__ = [
    "PerturbationLayer",
    "DartsModelAdapter",
    "generate_counterfactual",
    "generate_counterfactual_optuna",
    "generate_counterfactual_comet",
    "IPS_CLASSES",
    "IPS_ORDER",
    "IPS_WINDOWS",
    "BRGM_MIN_YEARS",
    "AQUIFER_IPS_WINDOW",
    "AQUIFER_CATEGORY",
    "compute_ips_reference",
    "compute_ips_reference_n",
    "compute_all_ips_references",
    "compute_ips_series",
    "compute_ips_series_n",
    "compute_rolling_monthly_mean",
    "validate_ips_data",
    "get_aquifer_ips_info",
    "daily_to_monthly_mean",
    "gwl_to_ips_class",
    "gwl_to_ips_zscore",
    "ips_class_to_gwl_bounds",
    "extract_scaler_params",
    "ref_stats_to_json",
    "ref_stats_from_json",
    "compute_monthly_ips_bounds",
    "classify_prediction_monthly",
    "validity_ratio",
    "stepwise_validity",
    "seasonal_validity",
    "proximity_theta",
    "proximity_l1",
    "proximity_l2",
    "mean_absolute_change",
    "max_absolute_change",
    "relative_change_pct",
    "temporal_sparsity",
    "channel_sparsity",
    "total_variation",
    "cc_compliance",
    "cc_compliance_from_theta",
    "cc_compliance_from_stresses",
    "pastas_agreement",
    "param_count",
    "convergence_iter",
    "wall_clock_seconds",
    "build_paper_metrics",
    "CounterfactualResult",
    "PASTAS_AVAILABLE",
    "PastasWrapper",
    "compute_rmse",
    "validate_with_pastas",
    "fit_pastas_for_station",
    "build_pastas_series_from_data",
    "cf_stresses_to_pastas_series",
    "run_dual_validation_for_results",
]
